### ISSUE TITLE
Class 'sjaakp\illustrated\Uploader' not found 

### ISSUE THREAD

**Issue by MagSag** [sjaakp/yii2-illustrated-behavior#11]
Hello, here are my problems
First,  In my view I am getting this error and I don't know what is the problem.

Second, I have an model to which I want  to attach more than 2 images(each image must be stored in it normal size and small sizes(32x32,96x96,110x140)); how can I do that?
Third, seeing the imgAttribute,sizeAttribute,cropeSize I really don't understand how should I use them an d, I would like to know how illustrated store these link (it generates).

**Comment by sjaakp** [comment]
IllustratedBehavior now supports multiple images.

**Comment by MagSag** [comment]
but how?
