### ISSUE TITLE
crop not applied

### ISSUE THREAD

**Issue by raoul2000** [sjaakp/yii2-illustrated-behavior#12]
Hi,
I'm using 1.1.0 on a very basic case copied from the README. The upload is ok, but the crop is not applied. I've noticed that even if the POST request does include the JSON crop hash, it is no assigned to [$crop](https://github.com/sjaakp/yii2-illustrated-behavior/blob/master/Illustration.php#L84) which remains NULL.

any idead how to fix this ?

Thanks

**Comment by argearriojas** [comment]
Hi @raoul2000 

Same problem here. Did you find a way to make it work?

**Comment by argearriojas** [comment]
I've found this trace message at the debug log:

Failed to set unsafe attribute '__picture_crop__'

Any ideas on how to fix this?

**Comment by raoul2000** [comment]
no, i didn't find a way so i wrote my own ...
