### ISSUE TITLE
I am getting error;Undefined index: photo

### ISSUE THREAD

**Issue by MagSag** [sjaakp/yii2-illustrated-behavior#15]
Is there any complete example of how to use the behavior(configuration in model,view,controller) and what are requirements to use the extension(which libraries are need). I am confused I don't know what to do things that I am trying are not working:
In my model:

 public $photo;//The file attributes 
     public function behaviors(){
        return [
            [
                "class" => "sjaakp\illustrated\Illustrated",
                "attributes"=>[
                    'img'=>[
                        'aspectRatio'=>1.0,
                        'cropSize'=>90,]
                ]
            ],
        ];
    }
//rules :  $rules[] = ['photo','file'];

In my view 
use sjaakp\illustrated\Uploader;

        <div id="partiechargee" class="panel panel-default center-block">
            <?php if($titre==true){
             echo '<p class="well-sm">';
           $this->render('/_alert', ['module' => $module,]);
            echo '</p>';}?>
            
            <h3 class="panel-title panel-heading text-center" style="margin-bottom:5px;"><strong><?= Html::encode($this->title)?></strong></h3>
                <?php $form = ActiveForm::begin([
                     'id'=> 'form-registration',
                    'enableAjaxValidation'   => true,
                    'enableClientValidation' => false,
                    'method'=>'post',
                    'action'=>\Yii::$app->urlManager->createUrl(['settings/profilephoto']),
                'options'=>['class'=>'well-sm text-center',
                    'enctype'=>'multipart/form-data']]); ?>
<?= $form->field($model, 'photo')->widget(Uploader::className([ 
        'deleteOptions' => [
            'label' => '<i class="fa fa-trash"></i>', // Font Awesome icon
            'title' => 'Delete image'
        ]
    ])) ?>
  <p class="text-center">
                <?= Html::submitButton(Yii::t('app', 'Exit'), ['class' => 'btn btn-danger cancel btn-block']) ?>
             </p>
                <?php ActiveForm::end(); ?>
    </div>

With that I am getting errror : Undefined index: photo

**Comment by MagSag** [comment]
Here is the solution;

This :

public function behaviors(){
return [
[
"class" => "sjaakp\illustrated\Illustrated",
"attributes"=>[
'img'=>[
'aspectRatio'=>1.0,
'cropSize'=>90,]
]
],
];
}

Should be:

public function behaviors(){
return [
[
"class" => "sjaakp\illustrated\Illustrated",
"attributes"=>[
'photo'//Important to put the attribute of fileinput,
'img'=>[
'aspectRatio'=>1.0,
'cropSize'=>90,]
]
],
];
}

**Comment by sjaakp** [comment]
In fact you created a model with two Illustrations: one called ‘photo’, having the default options (aspectRatio = 1.0, cropSize =240), and the other called ‘img’ with aspectRatio = 1.0 and cropSize = 90.

 

Please, first try the simplest case, one illustration without any options:

 

class NicePlace extends ActiveRecord {

 

                public function behaviors()         {

                               return [

                                               ‘class’ => ‘sjaakp\illustrated\Illustrated’,

                                               ‘attributes’ => [

                                                               ‘photo’

                                               ]

                               ];

                }

}

 

In the view:

 

use sjaakp\illustrated\Uploader;

...

            <?= $form->field($model, 'photo')->widget(Uploader::className())  ?>

...

 

That’s really all.

  _____  

Sjaak Priester

 <mailto:sjaak@sjaakpriester.nl> sjaak@sjaakpriester.nl

**Comment by MagSag** [comment]
Thanks dear but I've solved that problem my preoccupations are the issue 16 and 14 for now.
