### ISSUE TITLE
composer problem, manually not work

### ISSUE THREAD

**Issue by gomonkey** [sjaakp/yii2-illustrated-behavior#6]
Hello I try to download from composer:

> Problem 1
    - The requested package sjaakp/yii2-illustrated-behavior could not be found in any version, there may be a typo in the package name.

>Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

>Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

>Installation failed, reverting ./composer.json to its original content.

And if i try to install manually in folder:
vendor/sjaakp/illustrated
then, i will back this error 
>ReflectionException
>Class sjaakp\illustrated\Illustrated does not exist

**Comment by nigelterry** [comment]
gomonkey

I have this problem too and I don't understand your solution above. Can you provide more detail?

**Comment by xavsio4** [comment]
Same for me

**Comment by xavsio4** [comment]
under vendor yiisoft/extensions.php you will have to add this
```php
'sjaakp/illustrated' => 
  array (
    'name' => 'sjaakp/illustrated',
    'version' => '1.3.0.0',
    'alias' => 
    array (
      '@sjaakp/illustrated' => $vendorDir . '/sjaakp/illustrated',
    ),
  ),
```
but that is really not the good way

**Comment by xavsio4** [comment]
you will have other problems in doing so.

**Comment by nagyt234** [comment]
Use the following command,  not the manual installation:
```
composer require sjaakp/yii2-illustrated-behavior "dev-master"
```

**Comment by MagSag** [comment]
I tried this composer require sjaakp/yii2-illustrated-behavior "dev-master" but still getting the error :+1: 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - sjaakp/yii2-illustrated-behavior dev-master requires yiisoft/yii2-jui * ->
 satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - Installation request for sjaakp/yii2-illustrated-behavior dev-master -> sa
tisfiable by sjaakp/yii2-illustrated-behavior[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by pistej** [comment]
This kind of error is caused by old fxp/composer-asset-plugin, simple solution is (update), (re)install fxp/composer-asset-plugin with command: 
`composer global require "fxp/composer-asset-plugin:~1.0.0"`
and tne you can run: 
`composer update`
