### ISSUE TITLE
all images end up on 240x240

### ISSUE THREAD

**Issue by philippfrenzel** [sjaakp/yii2-illustrated-behavior#8]
Hi,

looks like I can upload the images, I manage to get the dimensions to set, but everytime I save, it converts the image to be 240x240:( And even "scales" them down, so proportions (aspect) get's lost:(

Thanks for your help!

**Comment by philippfrenzel** [comment]
sample:
![image](https://cloud.githubusercontent.com/assets/2319890/6651026/f28024be-ca30-11e4-8c59-0c9b6c48835c.png)

**Comment by amlopezalonso** [comment]
You should take into account aspectRatio both in Uploader and in Illustrated behavior. For instance:

    public function behaviors(){
        return [
            [
                'class' => 'sjaakp\illustrated\Illustrated',
                ...
                'aspectRatio' => 0.75,
                ...
            ],
        ];
    }

In form:

    <?= $form->field($model, 'image')->widget(Uploader::className(), ['aspectRatio' => 0.75]) ?>

**Comment by philippfrenzel** [comment]
I agree, but as you can 'change' Ratio on switching e.g. Landscape it doesn't adopt ratio:( or am I doing something wrong?

**Comment by amlopezalonso** [comment]
Not sure as I haven't tested it but I guess if you want to have aspect ratio in Illustrated to change accordingly to the dynamic aspect ratio in Uploader you should include it as a field in your DB, then set aspectRatio in the behavior as the name of such attribute. Check aspectRatio definition in "Illustrated Options" chapter (float is for fixed aspect ratio -square in your case- string for attribute definition -hence dynamic, this should be what you are looking for-).

**Comment by philippfrenzel** [comment]
hmm, still don't get it to run... it's killing my pictures...:(
