### ISSUE TITLE
Please add a getImgUrl() method

### ISSUE THREAD

**Issue by amlopezalonso** [sjaakp/yii2-illustrated-behavior#9]
Though getImgHtml is very useful I think this could be enhanced adding a getImgUrl method for common linked thumbnails to a bigger image such as:

    Html::a($model->getImgHtml($size=100), $model->getImgUrl(), ['title' => $model->nombre, 'target' => '_blank']);

Thanks a lot for your excellent work!

**Comment by sjaakp** [comment]
Done! However, I've called it getImgSrc().
